ruqqus_access_token: ''
ruqqus_refresh_token: ''
ruqqus_id: ''
ruqqus_secret: ''
reddit_id: ''
reddit_agent: ''
reddit_secret: ''
feeds:
  - 'https://www.thegatewaypundit.com/feed/'
  - 'https://bigleaguepolitics.com/feed/'
  - 'https://www.dailywire.com/feeds/rss.xml'
guild_list:
  - 'dankmemes'
  - 'memes'
  - '4chan'
  - 'tia'
  - 'okbr'
  - 'avgr'
guilds:
  - 'politics'
  - 'news'
  - 'conservative'
linux:
  - 'debian'
  - 'linus'
  - 'linux'
  - 'redhat'
  - 'torvalds'
  - 'ubuntu'
programming:
  - 'guido van rossum'
  - 'pycon'
  - 'python'
  - '.py'
  - 'bash'
  - 'c++'
  - 'code'
  - 'coding'
  - 'emacs lisp'
  - 'git'
  - 'golang'
  - 'graphql'
  - 'javascript'
  - 'jquery'
  - 'json'
  - 'jupyter notebook'
  - 'laravel'
  - 'malware'
  - 'npm'
  - 'operating system'
  - 'open source'
  - 'php'
  - 'programming'
  - 'rss'
  - 'software'
  - 'sql'
  - 'windows'
  - 'yaml'
  - '.js'
politics:
  - 'ballot'
  - 'biden'
  - 'democrat'
  - 'gop'
  - 'government'
  - 'melania'
  - 'pelosi'
  - 'politics'
  - 'president'
  - 'republican'
  - 'sanders'
  - 'senate'
  - 'senator'
  - 'trump'
internet: 
  - 'artificial intelligence'
  - 'facebook'
  - 'google'
  - 'instagram'
  - 'internet'
  - 'reddit'
  - 'snapchat'
  - 'twitter'
gaming:
  - 'call of duty'
  - 'gaming'
  - 'minecraft'
  - 'nintendo'
  - 'playstation'
  - 'ps3'
  - 'ps4'
  - 'video game'
  - 'wii'
  - 'xbox'
censorship:
  - 'censor'
