client_id: ''
client_secret: ''
username: ''
password: ''
user_agent: ''
sub_list: ''
usernames:
  - 'AutoModerator'
  - 'AssistantBOT'
  - 'RepostSentinel'
  - 'MAGIC_EYE_BOT'
  - 'RepostSleuthBot'
  - 'Flair_Helper'
python:
  - 'guido van rossum'
  - 'pycon'
  - 'python'
  - '.py'
linux:
  - 'debian'
  - 'linus'
  - 'linux'
  - 'redhat'
  - 'torvalds'
  - 'ubuntu'
programming:
  - 'bash'
  - 'c++'
  - 'code'
  - 'coding'
  - 'emacs lisp'
  - 'git'
  - 'golang'
  - 'graphql'
  - 'javascript'
  - 'jquery'
  - 'json'
  - 'jupyter notebook'
  - 'laravel'
  - 'malware'
  - 'npm'
  - 'operating system'
  - 'open source'
  - 'php'
  - 'programming'
  - 'rss'
  - 'software'
  - 'sql'
  - 'windows'
  - 'yaml'
  - '.js'
politics:
  - 'ballot'
  - 'biden'
  - 'democrat'
  - 'gop'
  - 'government'
  - 'melania'
  - 'pelosi'
  - 'politics'
  - 'president'
  - 'republican'
  - 'sanders'
  - 'senate'
  - 'senator'
  - 'trump'
internet: 
  - 'artificial intelligence'
  - 'facebook'
  - 'google'
  - 'instagram'
  - 'internet'
  - 'reddit'
  - 'snapchat'
  - 'twitter'
gaming:
  - 'call of duty'
  - 'gaming'
  - 'minecraft'
  - 'nintendo'
  - 'playstation'
  - 'ps3'
  - 'ps4'
  - 'video game'
  - 'wii'
  - 'xbox'
